### ISSUE TITLE
Too much left turning tendency starting to roll on ground

### ISSUE THREAD

**Issue by D-ECHO** [it0uchpods/IDG-PA28X#8]
### Expected Behavior
Less left turning tendency (controllable with NWS/rudder only)

### Current Behavior
Very harsh left turning tendency when starting to roll, controllable only with full rudder+differential braking, normal again at about 20kts

### Steps to Reproduce

1. Start aircraft (automatic/manual)
2. Apply takeoff power
3. Release Brakes
4.

**Comment by it0uchpods** [comment]
yeah, its a little bit high.. i'll refine it.

**Comment by it0uchpods** [comment]
this is a ground reactions problem, not aero. Fix is on the way
